### ISSUE TITLE
Apply FLARE on long read sequencing (ONT)

### ISSUE THREAD

**Issue by EmelineLG60** [YeoLab/FLARE#14]
Hello everyone,

First of all, thank for reading me. I am a phd student in biology, and I am learning on my side some bio-informatics stuff, without any background. 

Since several months, I have hard time running correctly? FLARE on my data.

For context, we have done long read sequencing (Poly(A) enrichment, PromethION, R10 and guppy aligment) on two different samples : APOBEC1 alone and APOBEC1-RPS2 (like Brannan did in his paper in 2021 : Ribostamp). I want to highlight specific isoformes associated to ribosomes.

After running Flare protocol (no trouble for that, the readme file is pretty clear, thank to you), and doing metaplot, I see more editions in transcripts in my APOBEC1-RPS2 condition versus APOBEC1 alone. But, the different isn't really neat. I have lot of edition in the end off 3'UTR too.

After reading all the scripts python, I have found several parameters. I have played with some off them, but the result isn't neat too.

Did someone test that with recent R10 with ONT technology ? And what was your parameters for that ?

Thank you a lot for your help and advice,

Emeline

![Capture_git](https://github.com/YeoLab/FLARE/assets/168748929/787d4e20-7981-46d6-aadf-8e2c3ef449fc)

**Comment by ekofman** [comment]
Hi @EmelineLG60, ONT data is known for having a very high error rate, so that might explain what you see. Specifically, there are a lot of C>T errors in nanopore data from what I remember. So it might be hard to get a clear signal unless you subtract the apobec alone "edit" sites from the Apobec1-RPS2 edit set, since a lot of them might just represent sequencing errors.

**Comment by ekofman** [comment]
See the following: https://www.biorxiv.org/content/10.1101/2023.03.29.534691v2
